export const SET_MONTH ="SET_MONTH";
export const NEXT_MONTH ="NEXT_MONTH";
export const PREVIOUS_MONTH ="PREVIOUS_MONTH";
export const SET_YEAR ="SET_YEAR";
export const SELECT_DATE ="SELECT_DATE";
export const SET_TODAY ="SET_TODAY";
export const PREVIOUS_MONTH_SELECT_DATE ="PREVIOUS_MONTH_SELECT_DATE";
export const NEXT_MONTH_SELECT_DATE = "NEXT_MONTH_SELECT_DATE";